name: Truffle test

on: ['push']

jobs:
   primary_job:
#  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install Dependencies
      run: yarn
    - name: Install truffle and ganache-cli
      run: yarn global add truffle ganache-cli
    - name: Update PATH
      run: echo "$HOME/.yarn/bin" >> $GITHUB_PATH
    - name: Start ganache
      run: ganache-cli -p 7545 -a 4 -e 10&
    - name: Run truffle test
      run: truffle test
    - name: Stop ganache
      run: ps ax | grep ganache-cli | head -n1 | awk '{print $1}' | xargs kill

